### ISSUE TITLE
Changing HTTP method to get access token requires large copy+paste in code

### ISSUE THREAD

**Issue by zgoda-mobica** [mlavin/django-all-access#49]
To change HTTP method to retrieve access token requires subclassing Client class and copying whole get_access_token() method to just change 'post' to 'get' because these are hardocoded literals in a call to self.request(). Not a bug but this smells.

**Comment by mlavin** [comment]
In the web app flow (Authorization Code Grant), the request to retrieve the access token is required to be a POST by the RFC: https://tools.ietf.org/html/rfc6749#section-4.1.3

> 4.1.3.  Access Token Request
   The client makes a request to the token endpoint by sending the
   following parameters using the "application/x-www-form-urlencoded"
   format per Appendix B with a character encoding of UTF-8 in the HTTP
   request entity-body
