### ISSUE TITLE
django-all-access version 0.7.0 not compatible with django < 1.7.0

### ISSUE THREAD

**Issue by cjjavellana** [mlavin/django-all-access#50]
I'm using django 1.6.1 and after installing the latest version of django-all-access this error is thrown

```
UnknownMigration: Migration 'allaccess:0001_initial' probably doesn't exist.
Traceback (most recent call last):
  File "/home/vagrant/.venv/lib/python2.7/site-packages/south/migration/base.py", line 302, in migration
    migration = __import__(full_name, {}, {}, ['Migration'])
  File "/home/vagrant/.venv/lib/python2.7/site-packages/allaccess/migrations/0001_initial.py", line 4, in <module>
    from django.db import models, migrations
ImportError: cannot import name migrations
```

**Comment by mlavin** [comment]
Please see the release notes on using the latest version with Django < 1.7 http://django-all-access.readthedocs.org/en/v0.7.X/releases.html#v0-7-0-2014-09-07

> For those using Django < 1.7 and South < 1.0 you’ll need to add the SOUTH_MIGRATION_MODULES setting to point to the old South migrations.

> SOUTH_MIGRATION_MODULES = {
    'allaccess': 'allaccess.south_migrations',
}
