### ISSUE TITLE
Modify AccountAccess model to work with Django 1.8

### ISSUE THREAD

**Issue by KyleMarMc** [mlavin/django-all-access#51]
Django 1.8 changes the way ```models.DateTimeField``` works - the options ```auto_now_add```, ```auto_now``` and ```default``` are now [mutually exclusive](https://docs.djangoproject.com/en/1.8/ref/models/fields/#datefield). Removing the ```default``` parameter from ```created``` and ```modified``` in the ```AccountAccess``` model definition appears to fix the issue.

**Comment by mlavin** [comment]
Yep I'm a little behind on 1.8 support but this would be a welcome change for a PR.
