### ISSUE TITLE
Supported Django Versions

### ISSUE THREAD

**Issue by mlavin** [mlavin/django-all-access#54]
Upcoming bug fix release will add 1.8 support. I think that means it's time to drop support for everything <1.7 which means we can get rid of the South migrations.

**Comment by vyscond** [comment]
thanks for the heads-up. i noticed that there is no branch with this tag. where can i help you out to make this important update get here asap?

**Comment by mlavin** [comment]
v0.7.2 was tagged and released with 1.8 support http://django-all-access.readthedocs.org/en/latest/releases.html#v0-7-2-2015-05-13 It case is for the next release milestone and working towards 1.0.

**Comment by vyscond** [comment]
Yeah. After posting here, i was looking at the commits and found the update. So i think it's time to close this one right?

**Comment by mlavin** [comment]
No this should not be closed. There is remaining work here for the next release: removing South migrations, updating the CI configuration, and explicitly documenting supported Django versions.

**Comment by mlavin** [comment]
Fixed by #61.
