### ISSUE TITLE
additional parameters (scopes) as settings constant

### ISSUE THREAD

**Issue by vyscond** [mlavin/django-all-access#57]
I've read the example over the docs of how we can override the __get_additional_parameters__ function. Since most of the backends are now running version 2.x i think we can provide a less "intrusive"  way to pass extra scopes.

The proposal is to change the default __get_additional_parameters__ from OAuthRedirect to 

```python
    def get_additional_parameters(self, provider):
        "Return additional redirect parameters for this provider."
        scopes = {}
        try:
            delimiter = settings.ALLACCESS[provider.name]['scopes']['delimiter']
            scopes = {
                'scope': delimiter.join(settings.ALLACCESS[provider.name]['scopes']['values'])
            }
        except AttributeError:
            print('no settings for {}'.format(provider.name))
        return scopes
```

so we can just append something like this over the settings:

```python
ALLACCESS = {
    'facebook': {
        'scopes': {
            'delimiter': ',',
            'values': ['email']
        }
    },
    'google': {
        'scopes': {
            'delimiter': ' ',
            'values': [
                'https://www.googleapis.com/auth/userinfo.profile',
                'https://www.googleapis.com/auth/userinfo.email'
            ]
        }
    }
}
```

I think most of the devs will need extra scopes always (the email address is always out of the default one) so this prevent to build a custom  __OAuthRedirect__ object just because we need more scopes.

**Comment by mlavin** [comment]
I think improving the way `scope` or other parameters are added would be great but I don't like the idea of doing this via settings. It would be more fitting to the approach of this project to either allow this to be passed in the url conf such as
```
...
url(r'^login/facebook/$', OAuthRedirect.as_view(params={'scopes': 'email'})),
url(r'^login/(?P<provider>(\w|-)+)/$', OAuthRedirect.as_view(), name='allaccess-login'),
...
```
or by configuring on the `Provider` record. I would lean toward the former since I don't think there is a great way to store this mapping in the database.

**Comment by vyscond** [comment]
I really like setting's variables :) but yeah the URLs params seems more appropriated to the project. I will cast the modifications to this on my fork. Thanks again.
