### ISSUE TITLE
missing email field on info (user profile)

### ISSUE THREAD

**Issue by vyscond** [mlavin/django-all-access#58]
I override the __get_or_create_user__ to include the user's email on the process of creating the new Django's user but it seems that the email is not comming along with the base request for the profile. I'm currently testing only with __facebook__. I'm sure that i passed the correct scopes for this type of request. It's shows up on the login window that i'am requesting "email" and i was testing with my own profile which i provided an public email. :/

So i kinda confusing here. The facebook page is not much clear if the email come along through the profile url  or i need to make additional request.

my __get_additional_parameters__ is the same [from the docs](http://django-all-access.readthedocs.org/en/latest/customize-views.html#additional-scope-example)

and here is the __get_or_create_user__

```python
class OAuthScopedCallback(OAuthCallback):

    def get_or_create_user(self, provider, access, info):
        user = super(OAuthScopedCallback, self).get_or_create_user(provider, access, info)
        # Check for a name
        print('Check for a name')
        try:
            names = info['name'].split()
            user.first_name = names[0]
            if len(names) > 1:
                user.last_name = names[-1]
            else:
                user.last_name = ''
        except:
            print('no names :(')
        # Check for a email
        print('Check for a email')
        try:
            user.email = info['email']
        except:
            print('no email, bitch! :(')
        user.save()
        return user
```

**Comment by mlavin** [comment]
What is the output here? What's the value of `info`? Note that `get_or_create_user` is only called during `handle_new_user`, that is if you've previously authenticated via Facebook and your user matches an `AccountAccess` then it won't be called.

**Comment by vyscond** [comment]
Yeah that's why i choose to override this method. I wanted to fill up this infos right up on the user model creation. Here is the output of the __info__: ```{'name': 'Ramon Moraes', 'id': '1653467144933268'}```.

**Comment by mlavin** [comment]
There you go. Facebook didn't give you the email: https://developers.facebook.com/docs/facebook-login/permissions/v2.4#reference-email

> Note, even if you request the email permission it is not guaranteed you will get an email address. For example, if someone signed up for Facebook with a phone number instead of an email address, the email field may be empty.

**Comment by vyscond** [comment]
Hum. I'm pretty sure that my account was maded with email! .-.

**Comment by mlavin** [comment]
The first sentence if more important than the second, which is only one example why it may be missing. Facebook doesn't have any way to guarantee you will get an email back. Twitter does not provide any way to get the user's email. If you require an email then you will have to enforce that in your application.  I think there is an open case to document this as a workflow customization. The basic follow would be to store the `AccountAccess` in the session redirect the user to a new form to give the email. Once you have the email, you would create the user and associate with the `AccountAccess`. Email verification would be another potential step.

**Comment by vyscond** [comment]
Yeah. Thanks again for the help! I will try to put an example of this over my fork before the pull

**Comment by mlavin** [comment]
Closing because I don't believe there is anything to address here. This project doesn't claim to guarantee the email will available for the newly created because it can't in general for any provider.
