### ISSUE TITLE
Facebook API not returning email and last_name

### ISSUE THREAD

**Issue by frostblooded** [mlavin/django-all-access#74]
I am using the Facebook API, but it isn't returning the user's email and last_name. I have set the fields and scope parameters and they seem to be sending correctly, but the info that the json response returns doesn't have the correct data. It is as if no params were sent with the request.

My repo can be found [here](https://github.com/frostblooded/image_site/tree/social_auth)

**Comment by mlavin** [comment]
Your project doesn't appear to use this app. It looks like it uses https://github.com/pennersr/django-allauth

**Comment by frostblooded** [comment]
It used it yesterday, but I had to change it because of this problem. You can see the previous version that uses this app [here](https://github.com/frostblooded/kanq/tree/ecdb74be217b6dc6f63e07d082c80a21813e8675)

**Comment by mlavin** [comment]
Looks like you've customized everything correctly to me. I'll have to investigate some more. It's worth noting that you are never guaranteed an email from the FB API as noted here: https://developers.facebook.com/docs/facebook-login/permissions#reference-email

> Note, even if you request the email permission it is not guaranteed you will get an email address. For example, if someone signed up for Facebook with a phone number instead of an email address, the email field may be empty.

Users are also able to decline any additional permissions other than `public_profile` so regardless of the app you chose to use, you'll need to handle the missing email case.

**Comment by frostblooded** [comment]
I see. This doesn't explain why I also couldn't get first_name and last_name though. I tried to look into the issue, but wasn't able to pinpoint it. I would be interested to help with what I can.

**Comment by mlavin** [comment]
Admittedly I haven't been keeping up with the recent changes in the FB API. The docs for this project currently recommend using https://graph.facebook.com/v2.8/me to get the user info after the login but there might be a better endpoint or it's missing some additional parameters to pass.

Let me know if you find anything and I'll be happy to merge in any fixes you have :heart:

**Comment by frostblooded** [comment]
I tried to use this endpoint through the browser and it returns everything just fine. I will be looking into it.

**Comment by frostblooded** [comment]
I just took another look at it and saw the problem immediately. Right now you are able to set the scope for the Facebook API, but you need to send some additional params ('fields') as of [version 2.4 of the Facebook API](https://developers.facebook.com/docs/apps/changelog). I made a pull request that adds the needed functionality.

#75
